### ISSUE TITLE
Breaking Fog integration tests

### ISSUE THREAD

**Issue by plribeiro3000** [fog/fog-ecloud#9]
The latest version `0.1.2` is breaking the integration tests in `fog`. 

I believe it could be this commit: 1642216afe8d519ab1417f0995a7ca3b21cf2edc

cc/ @stjeanp

**Comment by stjeanp** [comment]
Can you send me the output from the tests? The issue that this fixed was that if we access the /cloudapi/spec/... URLs, we have to use numeric access and secret keys, as per the Verizon docs. Without forcing those keys to be strings, it fails because it treats them as huge numbers.

I've run successful tests against our eCloud account, using a real key, as well as spec tests using their canned key. So I'm not sure what's breaking, but will be happy to track it down if you can point me in the right direction...

**Comment by plribeiro3000** [comment]
Take a look here: https://travis-ci.org/fog/fog/jobs/66264121

Fog master is currently broken because of that. And [this](https://github.com/fog/fog/blob/master/spec/fog/compute_spec.rb) is the broken test.

I'm not sure if that commit is the one, i just pointed it out because it is the only significant change from `0.1.1` to `0.1.2`. I would love if you could take a look at it. Thanks!

**Comment by stjeanp** [comment]
Ah hah! I think I found the issue. Let me try something here...

**Comment by plribeiro3000** [comment]
Awesome man. I believe that the issue might be because the code is always converting to string, so if you pass nothing it will get an empty string which is different of `nil`.

**Comment by stjeanp** [comment]
Could be. I'm adding some sanity checks now that return what the tests expect.

**Comment by stjeanp** [comment]
Ok, I've reproduced the issue, and yeah, that was it. So I moved the force to string to the else, and added a check to make sure that both a private key and an access key are supplied. It now throws an argument error with no credentials, works with real api keys, and works with the spec api keys.

I'm going to make a pull request in a minute...

**Comment by plribeiro3000** [comment]
Awesome man! Thanks! You rock :facepunch:
